In [94]:
!ls

 Bangla_FastText_cbow.pickle	 bangla_word2vec
'CRF For Bangla.ipynb'		 bangla_word2vec_gen4.zip
'CRF for English.ipynb'		 bangla_word2vec_gen4.zip.1
 DeepLearning.ipynb		 bangla_word2vec_gen4.zip.2
 Getting_Started.ipynb		 bangla_word2vec_gen4.zip.3
'Learning Deep Learning.ipynb'	 bengali-stemmer
 N.inb				'dhanda nlp.ipynb'
 NLP.ipynb			 new-workspace.jupyterlab-workspace
 archive.zip			 nlp_hackathon_bd_2023
 bangla-fasttext		 word2vec.ipynb


In [95]:
def getDatasetFromIBOFile(filename): #nlp_hackathon_bd_2023/data/dev.txt"
    f = open(filename, "r")
    content = f.read()
    
    lines = content.split("\n")
    
    dataset = []
    for line in lines:
        parts = line.split(" _ _ ")
        word = parts[0]
        label = parts[len(parts)-1]

        dataset.append([word,label])
    return dataset


In [96]:
dataset = getDatasetFromIBOFile("nlp_hackathon_bd_2023/data/dev.txt")
print(dataset[:30])

[['তিনি', 'O'], ['যুবক', 'O'], ['হিসেবে', 'O'], ['শেফিল্ড', 'B-GRP'], ['বুধবার', 'I-GRP'], ['এফ.সি.', 'I-GRP'], ['যোগদান', 'O'], ['করেন', 'O'], ['এবং', 'O'], ['১৯৫১', 'O'], ['সালে', 'O'], ['তাদের', 'O'], ['পেশাগত', 'O'], ['দিক', 'O'], ['দিয়ে', 'O'], ['আত্মপ্রকাশ', 'O'], ['করেন।', 'O'], ['', ''], ['ভিনেগার', 'O'], ['মাঝে', 'O'], ['মাঝে', 'O'], ['চাটনি', 'B-PROD'], ['ব্যবহার', 'O'], ['করা', 'O'], ['হয়।', 'O'], ['', ''], ['মূলত,', 'O'], ['দুর্গটি', 'O'], ['ছিল', 'O'], ['একটি', 'O']]


In [97]:
!pip install bltk

Keyring is skipped due to an exception: 'keyring.backends'


In [98]:
from bltk.langtools import PosTagger
pos_tagger = PosTagger()

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator DictVectorizer from version 0.21.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.21.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator Pipeline from version 0.21.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [99]:
# Convert data into features

feature_extracted_dataset = []
sentence = []
for row in dataset:
    word = row[0]
    label = row[1]
    if word=='':
        feature_extracted_dataset.append(sentence)
        sentence = []
        continue
    basic_word_features = (word, pos_tagger.pos_tag([word])[0][1], label)
    sentence.append(basic_word_features)
    

In [100]:
print(feature_extracted_dataset[:5])

[[('তিনি', 'PPR', 'O'), ('যুবক', 'NC', 'O'), ('হিসেবে', 'PP', 'O'), ('শেফিল্ড', 'NP', 'B-GRP'), ('বুধবার', 'NC', 'I-GRP'), ('এফ.সি.', 'NP', 'I-GRP'), ('যোগদান', 'NC', 'O'), ('করেন', 'VM', 'O'), ('এবং', 'CCD', 'O'), ('১৯৫১', 'RDX', 'O'), ('সালে', 'NC', 'O'), ('তাদের', 'PPR', 'O'), ('পেশাগত', 'JJ', 'O'), ('দিক', 'NC', 'O'), ('দিয়ে', 'VM', 'O'), ('আত্মপ্রকাশ', 'NC', 'O'), ('করেন।', 'VM', 'O')], [('ভিনেগার', 'NC', 'O'), ('মাঝে', 'NST', 'O'), ('মাঝে', 'NST', 'O'), ('চাটনি', 'NC', 'B-PROD'), ('ব্যবহার', 'NC', 'O'), ('করা', 'NV', 'O'), ('হয়।', 'VM', 'O')], [('মূলত,', 'NC', 'O'), ('দুর্গটি', 'NC', 'O'), ('ছিল', 'VM', 'O'), ('একটি', 'JQ', 'O'), ('সুরক্ষিত', 'JJ', 'O'), ('দুর্গ,', 'PU', 'O'), ('যা', 'PRL', 'O'), ('পোলিশ', 'NC', 'B-LOC'), ('-লিথুয়ানিয়ান', 'NC', 'I-LOC'), ('কমনওয়েলথ', 'NP', 'I-LOC'), ('এর', 'PPR', 'O'), ('দক্ষিণ', 'JJ', 'O'), ('সীমান্ত', 'NC', 'O'), ('রক্ষা', 'NC', 'O'), ('করে।', 'VM', 'O')], [('হার্নান্দেজ', 'NC', 'O'), ('আলোকচিত্রগ্রাহী', 'NC', 'B-PROD'), ('ফিল্ম', 'NP', 'I

# Old Model

In [77]:
def count_punctuations(text):
    punctuations='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~'
    cnt = 0
    for i in punctuations:
        if i in text:
            cnt += 1
    return cnt
print(count_punctuations("মূলত-প্রশংসা"))

1


In [78]:
def word2features(sent, i):
    word = sent[i][0]
    postag = sent[i][1]

    features = {
        'bias': 1.0,
        #'word.lower()': word.lower(),
        'word[-3:]': word[-3:],
        'word[-2:]': word[-2:],
        #'word.isupper()': word.isupper(),
        #'word.istitle()': word.istitle(),
        'word.isdigit()': word.isdigit(),
        'postag': postag,
        'postag[:2]': postag[:2],
        "containPunctuation": count_punctuations(word),
    }
    if i > 0:
        word1 = sent[i-1][0]
        postag1 = sent[i-1][1]
        features.update({
            #'-1:word.lower()': word1.lower(),
            #'-1:word.istitle()': word1.istitle(),
            #'-1:word.isupper()': word1.isupper(),
            '-1:postag': postag1,
            '-1:postag[:2]': postag1[:2],
        })
    else:
        features['BOS'] = True

    if i < len(sent)-1:
        word1 = sent[i+1][0]
        postag1 = sent[i+1][1]
        features.update({
            #'+1:word.lower()': word1.lower(),
            #'+1:word.istitle()': word1.istitle(),
            #'+1:word.isupper()': word1.isupper(),
            '+1:postag': postag1,
            '+1:postag[:2]': postag1[:2],
        })
    else:
        features['EOS'] = True

    return features


def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]

def sent2labels(sent):
    return [label for token, postag, label in sent]

def sent2tokens(sent):
    return [token for token, postag, label in sent]

In [79]:
X = [sent2features(s) for s in feature_extracted_dataset]
y = [sent2labels(s) for s in feature_extracted_dataset]

In [83]:
X[:2]

[[{'bias': 1.0,
   'word[-3:]': 'িনি',
   'word[-2:]': 'নি',
   'word.isdigit()': False,
   'postag': 'PPR',
   'postag[:2]': 'PP',
   'containPunctuation': 0,
   'BOS': True,
   '+1:postag': 'NC',
   '+1:postag[:2]': 'NC'},
  {'bias': 1.0,
   'word[-3:]': 'ুবক',
   'word[-2:]': 'বক',
   'word.isdigit()': False,
   'postag': 'NC',
   'postag[:2]': 'NC',
   'containPunctuation': 0,
   '-1:postag': 'PPR',
   '-1:postag[:2]': 'PP',
   '+1:postag': 'PP',
   '+1:postag[:2]': 'PP'},
  {'bias': 1.0,
   'word[-3:]': 'েবে',
   'word[-2:]': 'বে',
   'word.isdigit()': False,
   'postag': 'PP',
   'postag[:2]': 'PP',
   'containPunctuation': 0,
   '-1:postag': 'NC',
   '-1:postag[:2]': 'NC',
   '+1:postag': 'NP',
   '+1:postag[:2]': 'NP'},
  {'bias': 1.0,
   'word[-3:]': 'ল্ড',
   'word[-2:]': '্ড',
   'word.isdigit()': False,
   'postag': 'NP',
   'postag[:2]': 'NP',
   'containPunctuation': 0,
   '-1:postag': 'PP',
   '-1:postag[:2]': 'PP',
   '+1:postag': 'NC',
   '+1:postag[:2]': 'NC'},
  {'bi

In [84]:
from sklearn_crfsuite import CRF

crf = CRF(algorithm='lbfgs',
          c1=0.1,
          c2=0.1,
          max_iterations=100,
          all_possible_transitions=False)

In [86]:
!pip install sklearn

Keyring is skipped due to an exception: 'keyring.backends'


In [88]:
from sklearn.model_selection import cross_val_predict
from sklearn_crfsuite.metrics import flat_classification_report


In [90]:
pred = cross_val_predict(estimator=crf, X=X, y=y, cv=5)
report = flat_classification_report(y_pred=pred, y_true=y)
print(report)


              precision    recall  f1-score   support

      B-CORP       0.36      0.16      0.22       127
        B-CW       0.10      0.03      0.04       120
       B-GRP       0.47      0.34      0.39       118
       B-LOC       0.40      0.23      0.29       101
       B-PER       0.48      0.43      0.46       144
      B-PROD       0.39      0.15      0.22       189
      I-CORP       0.46      0.26      0.33       122
        I-CW       0.24      0.07      0.11       161
       I-GRP       0.58      0.44      0.50       226
       I-LOC       0.23      0.11      0.15        61
       I-PER       0.51      0.45      0.48       180
      I-PROD       0.36      0.21      0.27       128
           O       0.91      0.98      0.94      8648

    accuracy                           0.86     10325
   macro avg       0.42      0.30      0.34     10325
weighted avg       0.82      0.86      0.84     10325



# New Model
https://www.depends-on-the-definition.com/sequence-tagging-lstm-crf/

In [101]:
data = feature_extracted_dataset

In [115]:
words = list(set(word[0] for sentence in data for word in sentence))
words.append("ENDPAD")
n_words = len(words); n_words
print(words[:10])

['পরিচালনা', 'দুবার', '১৯৪২', 'কনস্ট্যান্স', 'অভিনেতা,', 'আকার', 'কাপড়ের', 'মারিয়া', 'প্রাসাদ', 'তারপরে,']


In [128]:
tags = list(set(word[2] for sentence in data for word in sentence))
n_tags = len(tags); n_tags

13

In [129]:
sentences = data
print(sentences[0])

[('তিনি', 'PPR', 'O'), ('যুবক', 'NC', 'O'), ('হিসেবে', 'PP', 'O'), ('শেফিল্ড', 'NP', 'B-GRP'), ('বুধবার', 'NC', 'I-GRP'), ('এফ.সি.', 'NP', 'I-GRP'), ('যোগদান', 'NC', 'O'), ('করেন', 'VM', 'O'), ('এবং', 'CCD', 'O'), ('১৯৫১', 'RDX', 'O'), ('সালে', 'NC', 'O'), ('তাদের', 'PPR', 'O'), ('পেশাগত', 'JJ', 'O'), ('দিক', 'NC', 'O'), ('দিয়ে', 'VM', 'O'), ('আত্মপ্রকাশ', 'NC', 'O'), ('করেন।', 'VM', 'O')]


In [130]:
max_len = 75
word2idx = {w: i + 1 for i, w in enumerate(words)}
tag2idx = {t: i for i, t in enumerate(tags)}

In [132]:
word2idx["যুবক"]
tag2idx["O"]

0

### Prepare the sentences

In [133]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X = [[word2idx[w[0]] for w in s] for s in sentences]

In [134]:
X = pad_sequences(maxlen=max_len, sequences=X, padding="post", value=0)

In [135]:
y = [[tag2idx[w[2]] for w in s] for s in sentences]

In [137]:
y = pad_sequences(maxlen=max_len, sequences=y, padding="post", value=tag2idx["O"])

In [138]:
from keras.utils import to_categorical
y = [to_categorical(i, num_classes=n_tags) for i in y]

In [139]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.1)

In [140]:
print(X_tr)

[[1412  110  700 ...    0    0    0]
 [4662 2651   78 ...    0    0    0]
 [2654 2436 1270 ...    0    0    0]
 ...
 [ 946 3025 1270 ...    0    0    0]
 [4704 4647 3193 ...    0    0    0]
 [2869 2809 3192 ...    0    0    0]]


In [143]:
print(y_tr[:2])

[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0.,

### Train the model

In [167]:
!ls keras-contrib/

CODEOWNERS	 PULL_REQUEST_TEMPLATE.md  examples	  tests
CONTRIBUTING.md  README.md		   keras_contrib
GUIDELINES.md	 contrib_docs		   pytest.ini
LICENSE		 convert_to_tf_keras.py    setup.py


In [172]:
# https://stackoverflow.com/questions/58498107/how-to-use-crf-in-tensorflow-keras
!pip install seqeval==0.0.5
!pip install keras==2.2.4

!git clone https://www.github.com/keras-team/keras-contrib.git
#!cd keras-contrib
!ls
!python keras-contrib/setup.py install

!pip install tensorflow==1.14.0

Keyring is skipped due to an exception: 'keyring.backends'
Keyring is skipped due to an exception: 'keyring.backends'
fatal: destination path 'keras-contrib' already exists and is not an empty directory.
 Bangla_FastText_cbow.pickle	 bangla_word2vec_gen4.zip
'CRF For Bangla.ipynb'		 bangla_word2vec_gen4.zip.1
'CRF for English.ipynb'		 bangla_word2vec_gen4.zip.2
 DeepLearning.ipynb		 bangla_word2vec_gen4.zip.3
 Getting_Started.ipynb		 bengali-stemmer
'Learning Deep Learning.ipynb'	'dhanda nlp.ipynb'
 N.inb				 keras-contrib
 NLP.ipynb			 new-workspace.jupyterlab-workspace
 archive.zip			 nlp_hackathon_bd_2023
 bangla-fasttext		 word2vec.ipynb
 bangla_word2vec
running install
/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/opt/conda/lib/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInsta

In [176]:
!rm keras-contrib -rf
!git clone https://github.com/tsterbak/keras-contrib.git
!python keras-contrib/setup.py install

Cloning into 'keras-contrib'...
remote: Enumerating objects: 2329, done.
remote: Total 2329 (delta 0), reused 0 (delta 0), pack-reused 2329
Receiving objects: 100% (2329/2329), 478.33 KiB | 8.70 MiB/s, done.
Resolving deltas: 100% (1461/1461), done.
running install
/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/opt/conda/lib/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 4.0.0-unsupported is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
running bdist_egg
running egg_info
writing keras_cont

In [177]:
from tensorflow import keras
from keras.models import Model
from tensorflow.keras.layers import Input
from keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from keras_contrib.layers import CRF


In [178]:
input = Input(shape=(max_len,))
model = Embedding(input_dim=n_words + 1, output_dim=20,
                  input_length=max_len, mask_zero=True)(input)  # 20-dim embedding
model = Bidirectional(LSTM(units=50, return_sequences=True,
                           recurrent_dropout=0.1))(model)  # variational biLSTM
model = TimeDistributed(Dense(50, activation="relu"))(model)  # a dense layer as suggested by neuralNer
crf = CRF(n_tags)  # CRF layer
out = crf(model)  # output


AttributeError: Exception encountered when calling layer "crf_6" (type CRF).

in user code:

    File "/opt/conda/lib/python3.7/site-packages/keras_contrib/layers/crf.py", line 292, in call  *
        test_output = self.viterbi_decoding(X, mask)
    File "/opt/conda/lib/python3.7/site-packages/keras_contrib/layers/crf.py", line 564, in viterbi_decoding  *
        argmin_tables = self.recursion(input_energy, mask, return_logZ=False)
    File "/opt/conda/lib/python3.7/site-packages/keras_contrib/layers/crf.py", line 521, in _step  *
        return self.step(input_energy_i, states, return_logZ)
    File "/opt/conda/lib/python3.7/site-packages/keras_contrib/layers/crf.py", line 463, in step  *
        m = K.slice(states[3], [0, t], [-1, 2])

    AttributeError: module 'keras.backend' has no attribute 'slice'


Call arguments received by layer "crf_6" (type CRF):
  • X=tf.Tensor(shape=(None, 75, 50), dtype=float32)
  • mask=tf.Tensor(shape=(None, 75), dtype=bool)

# Even more complex model
The old model does not work for whatever reason so here we go again.

https://www.depends-on-the-definition.com/lstm-with-char-embeddings-for-ner/

In [190]:
max_len = 75
max_len_char = 10

In [191]:
word2idx = {w: i + 2 for i, w in enumerate(words)}
word2idx["UNK"] = 1
word2idx["PAD"] = 0
idx2word = {i: w for w, i in word2idx.items()}
tag2idx = {t: i + 1 for i, t in enumerate(tags)}
tag2idx["PAD"] = 0
idx2tag = {i: w for w, i in tag2idx.items()}

In [192]:
word2idx["যুবক"]
tag2idx["O"]

1

### Padding

In [195]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_word = [[word2idx[w[0]] for w in s] for s in sentences]
X_word = pad_sequences(maxlen=max_len, sequences=X_word, value=word2idx["PAD"], padding='post', truncating='post')

In [194]:
chars = set([w_i for w in words for w_i in w])
n_chars = len(chars)
print(n_chars)

91


In [196]:
char2idx = {c: i + 2 for i, c in enumerate(chars)}
char2idx["UNK"] = 1
char2idx["PAD"] = 0


In [197]:
X_char = []
for sentence in sentences:
    sent_seq = []
    for i in range(max_len):
        word_seq = []
        for j in range(max_len_char):
            try:
                word_seq.append(char2idx.get(sentence[i][0][j]))
            except:
                word_seq.append(char2idx.get("PAD"))
        sent_seq.append(word_seq)
    X_char.append(np.array(sent_seq))


NameError: name 'np' is not defined

In [189]:
from tensorflow import keras
from tensorflow.keras.layers import Input
from keras.models import Model
from keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Conv1D
from keras.layers import Bidirectional, concatenate, SpatialDropout1D, GlobalMaxPooling1D

word_in = Input(shape=(max_len,))
emb_word = Embedding(input_dim=n_words + 2, output_dim=20,
                     input_length=max_len, mask_zero=True)(word_in)

# input and embeddings for characters
char_in = Input(shape=(max_len, max_len_char,))
emb_char = TimeDistributed(Embedding(input_dim=n_chars + 2, output_dim=10,
                           input_length=max_len_char, mask_zero=True))(char_in)
# character LSTM to get word encodings by characters
char_enc = TimeDistributed(LSTM(units=20, return_sequences=False,
                                recurrent_dropout=0.5))(emb_char)

# main LSTM
x = concatenate([emb_word, char_enc])
x = SpatialDropout1D(0.3)(x)
main_lstm = Bidirectional(LSTM(units=50, return_sequences=True,
                               recurrent_dropout=0.6))(x)
out = TimeDistributed(Dense(n_tags + 1, activation="sigmoid"))(main_lstm)

model = Model([word_in, char_in], out)

In [187]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["acc"])
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_14 (InputLayer)          [(None, 75, 10)]     0           []                               
                                                                                                  
 input_13 (InputLayer)          [(None, 75)]         0           []                               
                                                                                                  
 time_distributed_9 (TimeDistri  (None, 75, 10, 10)  70          ['input_14[0][0]']               
 buted)                                                                                           
                                                                                                  
 embedding_11 (Embedding)       (None, 75, 20)       94260       ['input_13[0][0]']           

In [188]:
history = model.fit([X_word_tr,
                     np.array(X_char_tr).reshape((len(X_char_tr), max_len, max_len_char))],
                    np.array(y_tr).reshape(len(y_tr), max_len, 1),
                    batch_size=32, epochs=10, validation_split=0.1, verbose=1)


NameError: name 'X_word_tr' is not defined